version: '3'

services:
  redis:
    image: redis:latest
    container_name: boltcard.redis
    ports:
      - 6380:6379
    command: 
      - redis-server
      - redis.conf
      - --appendonly yes
      - --requirepass ${REDIS_PASS}
    volumes:
      - ./data/redis:/data
    restart: always

  boltcard_chatbot:
    image: boltcard-chatbot:latest
    container_name: boltcard.chatbot
    ports:
      - 7531:80
    volumes:
      - ./:/app
    environment:
      - REDIS_HOST=boltcard.redis
      - REDIS_PASS=${REDIS_PASS}
      - REDIS_PORT=6380
    restart: always