version: '3'

services:
  redis:
    image: redis:latest
    container_name: boltcard.redis
    ports:
      - 6379:6379
    command: 
      - redis-server
      - redis.conf
      - --appendonly yes
      - --requirepass ${REDIS_PASS}
    volumes:
      - ./data/redis:/data
    restart: always

  ngrok:
    image: ngrok/ngrok:latest
    container_name: boltcard.ngrok
    ports:
      - 4040:4040
    command:
      - http
      - boltcard.chatbot
      - --config=/etc/ngrok.yml
    volumes:
      - ./data/ngrok/ngrok.yaml:/etc/ngrok.yml
    restart: always

  boltcard_chatbot:
    image: boltcard-chatbot:latest
    container_name: boltcard.chatbot
    ports:
      - 80:7531
    volumes:
      - ./:/app
    environment:
      - REDIS_HOST=boltcard.redis
      - REDIS_PASS=${REDIS_PASS}
      - NGROK_ACTIVE=${NGROK_ACTIVE}
      - NGROK_WEB_INTERFACE=http://boltcard.ngrok:4040
    depends_on:
      - ngrok
    restart: always