version: '3'

services:
  redis:
    image: redis:latest
    container_name: boltcard.redis
    command: 
      - redis-server
      - redis.conf
      - --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data